name: Build and Push Docker Image 

on:
  push:
    paths:
      - 'tareas/deli_jero/**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -f tareas/deli_jero/Dockerfile -t jero110/gitaction:0.01 tareas/deli_jero

    - name: Push Docker Image
      run: docker push jero110/gitaction:0.01

    - name: Test Docker Container
      run: docker run --rm jero110/gitaction:0.01 python prueba1.py
