name: Test Schedule
on:
  schedule:
    - cron: '45 22 * * 1,3'

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check schedule
        run: echo "Scheduled job ran successfully."
