name: Scheduled and Manual Git Log
on:
  schedule:
    # Schedule the workflow to run every Monday and Wednesday at 11:25 UTC
    - cron: '34 22 * * 1,3'
  workflow_dispatch:  # This adds a manual trigger (button)

jobs:
  get_git_log:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Get Git Log
        run: |
          # Get the last 5 commits with commit message
          git log -n 5 --oneline
