name: Check for Remote Updates

on:
  schedule:
    - cron: '10 21 * * 1,3'  # Every Monday and Wednesday at 9:10 PM UTC
  workflow_dispatch:  # Allows manual triggers via the GitHub Actions UI

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Check out the repository to the GitHub Actions runner

      - name: Fetch from Remote
        run: git fetch origin  # Fetch updates from the 'origin' remote repository

      - name: Check for Updates
        run: |
          # Check for remote repository updates
          updates=$(git log HEAD..origin/HEAD --oneline)
          
          if [[ -n "$updates" ]]; then
            echo "There are updates in the remote repository:"
            echo "$updates"
          else
            echo "No updates in the remote repository."

