name: Get Git Log
on:
  workflow_dispatch: {}
  push:
    branches:
      - main  

jobs:
  get_git_log:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Get Git Log
        run: |
          # Get the last 5 commits (you can adjust this)
          git log -n 5 --oneline

