name: Fetch Upstream Updates
on:
  # Schedule-based trigger (example: every day at 12:00 UTC)
  schedule:
    - cron: "0 12 * * *"
  # Manual trigger via workflow dispatch
  workflow_dispatch:

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Add the upstream repository
      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/<upstream-owner>/<upstream-repo>.git
        # Ensure to replace <upstream-owner> and <upstream-repo> with the correct values

      # Step 3: Fetch from upstream
      - name: Fetch from Upstream
        run: git fetch upstream

      # Step 4: List Remote Branches
      - name: List Remote Branches
        run: git branch -r
        # This step helps confirm that the fetch worked correctly

      # Step 5: Print Recent Commits from Upstream
      - name: Print Recent Commits from Upstream
        run: |
          git log upstream/main --pretty=format:"%h - %an, %ar : %s" -n 5
        # Change 'main' to the appropriate default branch name in the upstream repository
        # Adjust the '-n 5' option to get a different number of recent commits


