name: Extra
on:
  schedule:
    - cron: '34 22 * * 1,3'  # Scheduled run at 22:34 UTC on Mondays and Wednesdays
  workflow_dispatch: {}  # Manual trigger

jobs:
  print_git_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire commit history

      - name: Print All Git Logs
        run: git log --oneline
